### ISSUE TITLE
Bug in rendering from url

### ISSUE THREAD

**Issue by 19majkel94** [seladb/StarTrack-js#1]
https://seladb.github.io/StarTrack-js/?u=vichyssoise&r=graphql-typescript&u=19majkel94&r=type-graphql&u=prismake&r=typegql&u=vesper-framework&r=vesper

![image](https://user-images.githubusercontent.com/10618781/38781796-f5a93c46-40ea-11e8-8a06-72d6f7609480.png)

**Comment by nietaki** [comment]
Same here, with different repos: https://seladb.github.io/StarTrack-js/?u=nietaki&r=rexbug&u=nietaki&r=crawlie&u=nietaki&r=hoplon&u=crowdhailer&r=raxx

**Comment by nietaki** [comment]
it looks like it starts showing when you add a fourth repository...

**Comment by seladb** [comment]
Thanks for reporting this bug!
I just pushed a fix to master, please try again and reopen this if you still see the issue

**Comment by nietaki** [comment]
Looks perfect now, thank you!
