### ISSUE TITLE
Deleted Stars

### ISSUE THREAD

**Issue by shivin9** [seladb/StarTrack-js#14]
Hi,

Thanks for creating StarTrack-js. I wanted to ask whether you track removed stars also as the star curve is always increasing.

Thanks,
Shivin

**Comment by seladb** [comment]
that's a very good point! unfortunately GitHub API does not provide any information on deleted stars. It only gives you the current stars on a certain repo and the date they were given.

There is no way to track deleted stars without a backend polling this data continuously and comparing with the previous data. The problem with having a backend (except for the efforts to build and maintain it) is that it'd required polling GitHub API at scale which might cause an issue with [GitHub's rate limiting](https://developer.github.com/v3/#rate-limiting)

**Comment by shivin9** [comment]
Thanks for the update!
