### ISSUE TITLE
Log graph

### ISSUE THREAD

**Issue by passcod** [seladb/StarTrack-js#15]
Same mechanism as #6, would be great to be able to see the stars over a log graph.

**Comment by seladb** [comment]
@passcod do you mean logarithmic graph

**Comment by passcod** [comment]
Yes ---- On Thu, 18 Jun 2020 22:43:48 -1200  notifications@github.com  wrote ----
@passcod do you mean logarithmic graph?

**Comment by seladb** [comment]
Sure that could be a nice feature. Do you know any Javascript library I can use to convert the raw data into logarithmic scale?

**Comment by passcod** [comment]
It's already built in to the chart library you use: https://apexcharts.com/docs/options/yaxis/#logarithmic

**Comment by seladb** [comment]
For some reason on logarithmic scale the zoom-in option doesn't work. Do you know why?

If this is a bug in Apexcharts we may consider removing the zoom-in/out icons when switching to logarithmic view

**Comment by passcod** [comment]
Sorry, don't know. Could probably open an issue on ApexCharts ---- On Fri, 19 Jun 2020 17:28:50 -1200  notifications@github.com  wrote ----
For some reason on logarithmic scale the zoom-in option doesn't work. Do you know why?
If this is a bug in Apexcharts we may consider removing the zoom-in/out icons when switching to logarithmic view

**Comment by seladb** [comment]
Maybe we can consider disabling the zoom in/out option when switching to logarithmic mode. Will you consider making this fix?

**Comment by passcod** [comment]
Sure

**Comment by seladb** [comment]
Thank you so much for your contribution!
