### ISSUE TITLE
Error occured: API rate limit exceeded

### ISSUE THREAD

**Issue by 19majkel94** [seladb/StarTrack-js#2]
I received this error:
![image](https://user-images.githubusercontent.com/10618781/50028729-ee4c1e80-fff0-11e8-8722-7be2ee7217a9.png)

I see some form in html but I can't find a way to fill it and make it work.
Can the api token be stored in localstorage and used automatically?

**Comment by seladb** [comment]
Yes, that's a good point. I have this feature in mind but I didn't find time to implement it yet.
Do you think you can implement it yourself and make a PR?

**Comment by 19majkel94** [comment]
Sorry, my programmers license doesn't allow me to use jQuery 😆 

Maybe I will find some time to figure it out.

**Comment by seladb** [comment]
Fixed! :)

**Comment by 19majkel94** [comment]
Great! 🎉 
But can you store the github token in local storage? It's annoying to enter it every time i open the page to see the stars 😉

**Comment by seladb** [comment]
Sure, I'll make that fix

**Comment by seladb** [comment]
I added this feature. Now on the GitHub Authentication page you can check a checkbox that allows to store the auth details to local storage. This checkbox isn't checked by default because saving auth details in local storage isn't safe, so you have to check it manually.

Please let me know if you have any questions or comments

**Comment by 19majkel94** [comment]
The problem is that it's not working now 😞 

![image](https://user-images.githubusercontent.com/10618781/50146562-4ebeb280-02b4-11e9-811f-22b114b7379b.png)

**Comment by seladb** [comment]
Found the bug and fixed it. Please try again

**Comment by 19majkel94** [comment]
Works great! Thanks! ❤️

**Comment by seladb** [comment]
Awesome! ❤️ 
Please don't forget to start this project ⭐️ :)
