### ISSUE TITLE
GitHub "User" Star History?

### ISSUE THREAD

**Issue by chonyy** [seladb/StarTrack-js#24]
Hi,

I love this project so much.
However, I'm just wondering is it possible to track the history of stars given to a **user** and not a repo?
As I know, there's no stargazer list for a specific user. 
So, I'm not really sure if it's possible.
I would really like to know how could we track it.

Any idea would be nice.

Thanks.

**Comment by seladb** [comment]
thanks @chonyy for the kind words!

Unfortunately, I don't think GitHub provides a way to track user stars. Also I'd like to better understand the use-case: how would you use "user star progress"? Usually people would like to know the state of a certain repo, not all of the repos in their account. Please let me know

**Comment by chonyy** [comment]
Hi,

I was just thinking that it would be pretty nice if I could show that kind of history on my GitHub Profile Card.
Something like this. 
https://github.com/vn7n24fzkq/github-profile-summary-cards

**Comment by seladb** [comment]
The GitHub Profile Summary looks great, but I'm not sure how StarTrack-js can track user star history, or even if it should. For example: should it track only stars? or maybe commits, PR and issues also? I think your idea can evolve into a whole new project :)
