### ISSUE TITLE
[ENH]: add switch to select exponential growth in forecast

### ISSUE THREAD

**Issue by MuellerSeb** [seladb/StarTrack-js#28]
Thanks for this nice tool! Saw the recently added forcast option and appreciate it very much!

One idea from my side: since growth is often exponentially with packages on Github, I think it could be nice to add a switch to choose between linear or exponential growth.

Cheers,
Sebastian

**Comment by MuellerSeb** [comment]
Since you already provide a "logarithmic scale" this is easily done by first transforming the data to their log-values and then using a Linear Least Squares regression.

**Comment by seladb** [comment]
Thanks @MuellerSeb , this is a good suggestion! Please feel free to implement it and open a PR if you have time

**Comment by MuellerSeb** [comment]
Unfortunately I am not very familiar with java-script. I am just a user at this point :-/

**Comment by seladb** [comment]
Got it, no worries. I'll try to add it when I have time

**Comment by seladb** [comment]
This was added quite some time ago. I think we can close this issue now
