### ISSUE TITLE
Is that possible to extend the repo limit from eight to a larger number?

### ISSUE THREAD

**Issue by zhimin-z** [seladb/StarTrack-js#49]
After trying it, I really love this tool!

However, I find it a bit inconvenient when we want to compare the star tracks between more than eight tools, wondering if we can extend the limit.

**Comment by seladb** [comment]
Thank you for the kind words @zhimin-z !

I think the limit can be extended. Basically need to change `maxReposAllowed` here: https://github.com/seladb/StarTrack-js/blob/a24246da58cbae0d0995acfdebf4b2b1fcc73b4c/src/utils/StargazerLoader.js#L15, and add a color here: https://github.com/seladb/StarTrack-js/blob/a24246da58cbae0d0995acfdebf4b2b1fcc73b4c/src/utils/StargazerLoader.js#L4

I think that's it, however we need to test it.

Would you consider opening a PR with this change?

**Comment by zhimin-z** [comment]
> Thank you for the kind words @zhimin-z !
> 
> I think the limit can be extended. Basically need to change `maxReposAllowed` here:
> 
> https://github.com/seladb/StarTrack-js/blob/a24246da58cbae0d0995acfdebf4b2b1fcc73b4c/src/utils/StargazerLoader.js#L15
> 
> , and add a color here:
> https://github.com/seladb/StarTrack-js/blob/a24246da58cbae0d0995acfdebf4b2b1fcc73b4c/src/utils/StargazerLoader.js#L4
> 
> I think that's it, however we need to test it.
> 
> Would you consider opening a PR with this change?

Thank you @seladb Please check this: https://github.com/seladb/StarTrack-js/pull/51

**Comment by seladb** [comment]
Thank you @zhimin-z for contributing to this project, I really appreciate it! 🙏 ❤️ 
Your PR https://github.com/seladb/StarTrack-js/pull/53 has been merged to `master`, I'm closing this issue now
