### ISSUE TITLE
Support for GitHub Gist

### ISSUE THREAD

**Issue by Hakky54** [seladb/StarTrack-js#56]
Currently there is no support gists, would be nice to have that also be tracked. Do you think that would be possible?
Example gist on github is: https://gist.github.com/Hakky54/b30418b25215ad7d18f978bc0b448d81

Normally StarTrack uses username and repo name. When using gists the usename is still present in the url howewer the repo name is an unique id.

**Comment by seladb** [comment]
This is a nice idea, please feel free to add support for it :)

**Comment by seladb** [comment]
I think you're right - GitHub doesn't have a gist stargazer API, hence it's not possible to support it 😞 

I think we can close this issue?

**Comment by Hakky54** [comment]
Yes let's close it for now
