### ISSUE TITLE
Zoom in does not work properly if multiple projects are tracked

### ISSUE THREAD

**Issue by omry** [seladb/StarTrack-js#9]
In the react branch, looks like the zoom is automatically determined based on the first tracked time series.

Try this zooming in here:
https://startrack-js.herokuapp.com/#/preload?r=facebookresearch,hydra&r=facebookresearch,TensorComprehensions

**Comment by seladb** [comment]
Yes this is indeed a bug, let me see what I can do

**Comment by seladb** [comment]
Apparently there is a bug in ApexCharts (the charts library I'm using):
https://github.com/apexcharts/apexcharts.js/issues/1260

An easy workaround would be to disable the `autoScaleYaxis` property, but when doing so the scale doesn't change at all when zooming in, which is also a pretty bad solution.

Another (ugly) workaround would be to disable this property when there are multiple series displayed.
 
I've left a comment on the ApexChart's issue, let's see if the author of this library can make a quick fix or suggest a workaround

**Comment by omry** [comment]
Let's see what they say. it does not sound like a hard bug to fix.

Your workarounds sounds good too in case they won't fix it.

BTW:
To get more feedback on the new UI, I suggest that you put a link to it as experimental new UI in the main readme.

**Comment by seladb** [comment]
I agree, let's give it a day or two. Otherwise I'll make the (ugly) workaround.

Apart from this bug, I'm basically ready to deploy version 2.0 😃 

It's definitely better comparing to the current version... I guess I can gather feedback once it's published. 
I also plan to deploy it on GitHub Pages (and not on Heroku where it's currently deployed) so the page loading time will be much faster.

If you have any feedback on the new release before I publish it please let me know.

**Comment by omry** [comment]
It seems to be in pretty good condition from the little I saw playing with it for a few minutes.
Maybe some time can be put into the appearance of the graphs, thinner lines, different color palette but nothing serious.

Ship it!

**Comment by seladb** [comment]
I made the workaround of disabling `autoScaleYaxis` if more than 1 repo is presented. Please let me know if you prefer to keep the issue open or close it

**Comment by omry** [comment]
I would keep this open as a reminder to check if ApexCharts addressed this from time to time.

**Comment by seladb** [comment]
This is solved in v3.0.0 since we moved from ApexChart to Plotly.js
